### ISSUE TITLE
this is already checked in test_auth

### ISSUE THREAD

**Issue by ScottJohnson02** [Thommond/tsct-portal#25]
https://github.com/Thommond/tsct-portal/blob/726cfcf86a15985093fd9002a2636478a2495e9e/tests/test_courses.py#L9

**Comment by Thommond** [comment]
The login and log out functions do not serve the purpose of checking the login to the full extent. They are meant so I can log in and log out during the tests to improve efficiency and reduce redundant post requests in all the tests.
